modLoader="javafml"
loaderVersion="[1,)"
issueTrackerURL="https://github.com/Mrbysco/NPCInvasion/issues"
license="MIT"

[[mods]]
modId="npcinvasion"
version="${file.jarVersion}"
displayName="NPC Invasion"
displayURL="https://www.curseforge.com/minecraft/mc-mods/npc-invasion"
authors="Mrbysco"
description='''
🍦 Hmmm Ice cream so good!
'''

[[dependencies.npcinvasion]]
modId="minecraft"
mandatory=true
versionRange="[1.20.2,1.21)"
ordering="NONE"
side="BOTH"
[[dependencies.npcinvasion]]
modId="neoforge"
mandatory=true
versionRange="[20.2.86,)"
ordering="NONE"
side="BOTH"