modLoader="javafml"
loaderVersion="[2,)"
issueTrackerURL="https://github.com/Mrbysco/NPCInvasion/issues"
license="MIT"

[[mods]]
modId="npcinvasion"
version="${file.jarVersion}"
displayName="NPC Invasion"
displayURL="https://www.curseforge.com/minecraft/mc-mods/npc-invasion"
authors="Mrbysco"
description='''
🍦 Hmmm Ice cream so good!
'''

[[dependencies.npcinvasion]]
modId="minecraft"
type="REQUIRED"
versionRange="[1.20.4,1.21)"
ordering="NONE"
side="BOTH"
[[dependencies.npcinvasion]]
modId="neoforge"
type="REQUIRED"
versionRange="[20.4.70-beta,)"
ordering="NONE"
side="BOTH"