modLoader="javafml"
loaderVersion="[4,)"
issueTrackerURL="https://github.com/Mrbysco/NPCInvasion/issues"
license="MIT"

[[mods]]
modId="npcinvasion"
version="${file.jarVersion}"
displayName="NPC Invasion"
displayURL="https://www.curseforge.com/minecraft/mc-mods/npc-invasion"
authors="Mrbysco"
description='''
🍦 Hmmm Ice cream so good!
'''

[[dependencies.npcinvasion]]
modId="minecraft"
type="required"
versionRange="[26.1.1,)"
ordering="NONE"
side="BOTH"
[[dependencies.npcinvasion]]
modId="neoforge"
type="required"
versionRange="[26.1.1.0-alpha,)"
ordering="NONE"
side="BOTH"